"""Reading the tone of a question, so the answer can match it.

Someone asking "is 6.9 potassium dangerous?" and someone asking "what
threshold does the classifier use for potassium?" want the same facts
delivered very differently. The first needs the answer to lead with
reassurance and clarity; the second wants the number.

Deliberately a lexicon rather than a model call. Detection has to finish
before generation starts, so a second round trip would sit directly in the
user's latency budget - and tone is one of the few things a word list genuinely
does well. It is also deterministic, which makes it testable; an LLM classifier
would not be.

The detected tone only ever adjusts *how* an answer is written. It never
changes which chunks are retrieved, or what facts are stated.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

_CUES: dict[str, tuple[str, ...]] = {
    "worried": (
        "worried", "worry", "worrying", "scared", "afraid", "anxious", "panic",
        "serious", "dangerous", "danger", "severe", "die", "dying", "fatal",
        "life threatening", "should i be", "am i ok", "am i going to",
        "how bad", "is it bad",
    ),
    "urgent": (
        "urgent", "urgently", "emergency", "immediately", "right now", "asap",
        "hospital", "a and e", "emergency room", "999", "911",
        "what do i do now",
    ),
    "confused": (
        "confused", "confusing", "dont understand", "don t understand",
        "do not understand", "unclear", "what does", "what is", "what are",
        "explain", "mean", "means", "meaning", "how does", "why does",
        "simpler", "plain english",
    ),
    "skeptical": (
        "accurate", "reliable", "trust", "trustworthy", "wrong", "proof",
        "prove", "how do you know", "why should i", "is this right",
        "hallucinate", "hallucination", "made up",
    ),
    "frustrated": (
        "not working", "doesn t work", "does not work", "broken", "error",
        "failed", "fails", "stuck", "annoying", "useless", "keeps failing",
    ),
}

# How each tone changes the writing, injected into the system prompt.
_DIRECTIVES: dict[str, str] = {
    "worried": (
        "The question sounds anxious. Lead with the single most reassuring "
        "true statement you can make, then the facts. Do not minimise a real "
        "concern, and do not dramatise. Keep sentences short."
    ),
    "urgent": (
        "The question sounds urgent. Put the action first, in the first "
        "sentence. Be brief. If the situation could be a medical emergency, "
        "say plainly that they should contact emergency services or a doctor "
        "now rather than read further."
    ),
    "confused": (
        "The question asks for an explanation. Define terms as you use them, "
        "give one concrete example, and prefer plain words over precise ones "
        "where the two conflict."
    ),
    "skeptical": (
        "The question challenges the system's reliability. Answer with "
        "specifics: what is computed by fixed rules, what is generated by a "
        "model, and where the thresholds come from. Do not be defensive, and "
        "state the limitations honestly."
    ),
    "frustrated": (
        "The question sounds like something is not working. Skip preamble and "
        "give the fix as concrete steps. If you do not know the cause, say so "
        "and name the next thing to check."
    ),
    "neutral": (
        "The question is straightforward. Answer directly and concisely, "
        "without padding or reassurance the reader did not ask for."
    ),
}

# Checked in this order: a question that is both urgent and confused is urgent
# first, because acting matters more than understanding in that moment.
_PRIORITY = ("urgent", "worried", "frustrated", "skeptical", "confused")

# Compiled once, anchored on word boundaries. The boundaries matter: with a
# plain substring test the cue "er" matched inside "dangerous" and
# "understand", which fired "urgent" on nearly every question asked.
_PATTERNS: dict[str, tuple[re.Pattern[str], ...]] = {
    label: tuple(re.compile(r"\b" + re.escape(cue) + r"\b") for cue in cues)
    for label, cues in _CUES.items()
}


@dataclass(frozen=True)
class Tone:
    """How a question was read."""

    label: str
    directive: str
    scores: dict[str, int]

    @property
    def is_neutral(self) -> bool:
        return self.label == "neutral"


def normalise(text: str) -> str:
    """Lowercase and strip punctuation so cues match contractions too.

    "don't understand" becomes "don t understand", which is why that spelling
    appears in the cue list alongside the apostrophe-free one.
    """
    stripped = re.sub(r"[^a-z0-9 ]+", " ", text.lower())
    return re.sub(r"\s+", " ", stripped).strip()


def detect_tone(question: str) -> Tone:
    """Read the tone of a question.

    Returns the highest-priority tone with at least one cue, or ``neutral``.
    """
    text = normalise(question)

    scores = {
        label: sum(1 for pattern in patterns if pattern.search(text))
        for label, patterns in _PATTERNS.items()
    }

    for label in _PRIORITY:
        if scores.get(label):
            return Tone(label=label, directive=_DIRECTIVES[label], scores=scores)

    return Tone(label="neutral", directive=_DIRECTIVES["neutral"], scores=scores)
