"""Pydantic schemas - the contract between React, FastAPI and the agent.

Every shape that crosses an HTTP boundary is declared here, so the API's
surface is described in one file and FastAPI can generate accurate docs from
it automatically.

Note that these describe the *transport* shape. The MCP tools exchange plain
dicts, and the agent converts tool output into these models on the way out.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

Severity = Literal["critical", "warning", "normal", "unknown"]
MatchedBy = Literal["exact", "alias", "fuzzy"]


# ---------------------------------------------------------------------------
# Input
# ---------------------------------------------------------------------------

class LabInput(BaseModel):
    """One lab result as submitted by the user."""

    test_name: str = Field(
        ...,
        min_length=1,
        max_length=120,
        description="Lab test name. Aliases and minor typos are tolerated.",
        examples=["Hemoglobin", "HGB", "Potassium"],
    )
    value: float | str = Field(
        ...,
        description="Measured value. Numeric strings and censored results "
                    "such as '<0.1' are accepted.",
        examples=[7.2, "92", "<0.1"],
    )
    unit: str | None = Field(
        default=None,
        max_length=40,
        description="Unit as reported. If omitted, the canonical unit for the "
                    "test is assumed and the assumption is flagged.",
        examples=["g/dL", "mEq/L"],
    )

    # A reference interval that arrived with the result. The Kaggle dataset
    # supplies Min_Reference/Max_Reference per row, and a laboratory's own
    # interval is authoritative for its own result, so these take precedence
    # over the built-in table.
    reference_low: float | None = Field(
        default=None,
        description="Lower bound of the reference interval supplied with the result.",
        examples=[150],
    )
    reference_high: float | None = Field(
        default=None,
        description="Upper bound of the reference interval supplied with the result.",
        examples=[450],
    )
    reference_text: str | None = Field(
        default=None,
        max_length=80,
        description="Expected qualitative result, for word-valued tests such "
                    "as urinalysis strips.",
        examples=["Negatif", "Normal"],
    )

    @field_validator("test_name")
    @classmethod
    def _not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("test_name cannot be blank")
        return value.strip()


class AnalyzeRequest(BaseModel):
    """Request body for POST /analyze_labs."""

    patient_id: str | None = Field(
        default=None,
        max_length=64,
        description="Optional free-form label, echoed back in the response.",
        examples=["ANON-0142"],
    )
    labs: list[LabInput] = Field(
        ...,
        min_length=1,
        description="Lab results to analyze.",
    )


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

class ReferenceRange(BaseModel):
    """The thresholds a value was compared against."""

    low: float
    high: float
    critical_low: float | None = None
    critical_high: float | None = None
    unit: str


class LabResult(BaseModel):
    """A single classified and explained lab result.

    Fields fall into three groups:

    * measurement    - what was submitted
    * classification - computed deterministically, never by the LLM
    * explanation    - generated by the LLM from the classification above
    """

    # --- measurement ---
    test_name: str
    value: float | str
    unit: str | None = None

    # --- classification (deterministic) ---
    severity: Severity
    band: str | None = None
    reference_range: ReferenceRange | None = None
    range_source: Literal["supplied", "internal", "none"] | None = Field(
        default=None,
        description="Where the reference interval came from: 'supplied' means "
                    "it arrived with the result (e.g. a dataset column), "
                    "'internal' means the built-in clinical table.",
    )
    critical_basis: Literal["table", "derived", "none"] | None = Field(
        default=None,
        description="How the critical thresholds were set. 'table' is a "
                    "published panic value; 'derived' is estimated from the "
                    "supplied interval's width and is indicative only.",
    )
    comparison: Literal["numeric", "qualitative"] | None = Field(
        default=None,
        description="Whether the value was compared as a number or as a word "
                    "(urinalysis strips report 'Negatif', '1+').",
    )
    direction: Literal["below", "above", "within", "differs"] | None = None
    deviation_pct: float | None = None
    deviation_text: str | None = None
    rule_fired: str | None = Field(
        default=None,
        description="The literal comparison that produced the severity, so a "
                    "user can verify the verdict rather than trust it.",
    )
    matched_by: MatchedBy | None = None
    unit_assumed: bool = False

    # --- clinical context (from the reference table) ---
    category: str | None = None
    specialty: str | None = None
    measures: str | None = None

    # --- explanation (from the LLM) ---
    explanation: str | None = Field(
        default=None,
        description="Clinical meaning of this result, generated by the LLM. "
                    "Null when the LLM was unavailable or the result could "
                    "not be interpreted.",
    )
    next_step: str | None = Field(
        default=None,
        description="Suggested clinical action, generated by the LLM.",
    )

    # --- diagnostics ---
    notes: str | None = None
    error: str | None = None


class RowError(BaseModel):
    """A row that could not be read at all, kept separate from results."""

    row: int | None = Field(default=None, description="1-based source row, for CSV input.")
    test_name: str | None = None
    raw: dict[str, Any] | None = None
    error: str


class Summary(BaseModel):
    """Counts by severity, for the header of the results view."""

    total: int = 0
    critical: int = 0
    warning: int = 0
    normal: int = 0
    unknown: int = 0
    abnormal: int = 0
    errors: int = 0


class ResponseMeta(BaseModel):
    """How the response was produced - useful for debugging and demos."""

    llm_provider: str
    llm_model: str | None = None
    llm_available: bool = True
    llm_error: str | None = Field(
        default=None,
        description="Set when explanations were unavailable. Classification "
                    "is unaffected: it never depends on the LLM.",
    )
    elapsed_ms: int = 0
    mcp_tools_used: list[str] = Field(default_factory=list)


class AnalyzeResponse(BaseModel):
    """Response body for POST /analyze_labs.

    ``results`` is pre-sorted by the Route step (critical first). The frontend
    renders in the order given and does not re-sort.
    """

    patient_id: str | None = None
    summary: Summary
    results: list[LabResult]
    errors: list[RowError] = Field(default_factory=list)
    meta: ResponseMeta


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Response body for GET /health."""

    status: Literal["ok", "degraded"]
    mcp_server: Literal["connected", "unavailable"]
    tools_available: list[str] = Field(default_factory=list)
    llm_provider: str
    llm_model: str | None = None
    detail: str | None = None
